# Generated by Django 4.2.2 on 2023-06-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingmember',
            name='meeting',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_member',
            field=models.ManyToManyField(to='meeting.meetingmember'),
        ),
    ]
