# Generated by Django 4.2.2 on 2023-06-18 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0002_remove_meetingmember_meeting_meeting_meeting_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_member',
            field=models.ManyToManyField(related_name='meeting_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MeetingMember',
        ),
    ]
