# Generated by Django 4.2.2 on 2023-06-19 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_request',
            name='creator_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information_request',
            name='information_answer',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='information_request',
            name='status',
            field=models.CharField(choices=[('o', 'Open'), ('c', 'Closed')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='information_request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
