# Generated by Django 4.2.2 on 2023-06-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_information_request_creator_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information_request',
            old_name='user_id',
            new_name='receiver_id',
        ),
    ]
